### PR TITLE
fix: use native strictEqual for the internal asserts

### LINKED ISSUE #13: The function `check` does some internal assertions using the `assert` function it receives as parameter
The enclosed function `check` uses the same `assert` function it receives as parameter to do some _internal checks_ on `time`, `pid` and `hostname`. It is unnecessary to use default assert function (`deepStrictEqual`) to check on these values and this behaviour also  makes it hard to create assessments on properties -- ie: when `chunkCopy` must contain some property `foo`, we also have to account for the `time`, `pid` and `hostname`.
 
https://github.com/pinojs/pino-test/blob/c22d2aba5a44f7d1cd51aed8f81ff70c1a046f7c/pino-test.js#L38

My suggestion is to to use standard `strictEqual` on the _internal checks_ and only use the `assert` function parameter on the payload (`chunkCopy`), itself. This is a suggestion of implementation:
```js
function check (chunk, expected, assert) {
  const { time, pid, hostname, ...chunkCopy } = chunk

  // internal assertions (*)
  nodeAssert.strictEqual(new Date(time) <= new Date(), true, 'time is greater than Date.now()')
  nodeAssert.strictEqual(pid, process.pid)
  nodeAssert.strictEqual(hostname, os.hostname())

  // "consumer" assertion
  assert(chunkCopy, expected)
}
```

PS: on a side note, I'm not sure whether it's actually useful to run these _internal assertions_ each time a consumer asserts on their logs, but maybe I'm missing something here

### PR DESCRIPTION
**Pull request by ruddenchaux**
1. the first commit fixes the internal assert
2. the second is a test refactor regrouping the tests by method name
3. the third renames the test titles

Closes #13

### CODE REVIEW

**Comment by ruddenchaux** [comment]
@mcollina can you please review it?

**Review by jsumners — COMMENTED** [review]
I don't understand the original issue. Why would this function use a different assertion library than the one provided?

**Comment by ruddenchaux** [comment]
Currently, if you want to use a custom assertion callback, you have to worry about the internals of the `check` function and this makes it hard to define custom assertion logic.

Let me show an example.

```js
// index.js
const crypto = require('node:crypto')

function businessLogic(loggerInstance) {
  loggerInstance.info({
    uuid: crypto.randomUUID(),
    foo: 'bar',
    baz: 'buz',
  })
}

module.exports = businessLogic
```

```js
// test.js
const {test} = require('node:test')
const assert = require('node:assert')
const pino = require('pino')
const pinoTest = require('pino-test')
const businessLogic = require('./index')

test('should log a random generated uuid', async () => {
  const stream = pinoTest.sink();
  const loggerInstance = pino(stream);

  businessLogic(loggerInstance);

  const expected = {
    foo: 'bar',
    baz: 'buz',
  }

  await pinoTest.once(stream, expected, (actual, expected) => {
    assert.ok(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(actual.uuid))
    assert.strictEqual(actual.foo, expected.foo)
    assert.strictEqual(actual.baz, expected.baz)
  })
})
```

The test will fail because the custom callback will be called 4 times by the internal `check` function and the first three times the `actual` will not be an object that contains the expected keys.

So if you want to do this kind of custom assert, you have to complicate the callback in an inappropriate way:

```js
await pinoTest.once(stream, expected, (actual, expected) => {
  if (actual.uuid) {
    assert.ok(/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(actual.uuid))
    assert.strictEqual(actual.foo, expected.foo)
    assert.strictEqual(actual.baz, expected.baz)
  }
})
```

**Comment by jsumners** [comment]
I would say that is due to your "custom callback" not actually being an "assert" function as `pinoTest.once` is expecting. The docs indicate that `assert()` is meant to be a function with the same signature as `nodeAssert.deepStrictEqual`: https://github.com/pinojs/pino-test/blob/c0bb52cf71420620701e77fd82466d5e42a266ba/pino-test.js#L47-L64

**Comment by ruddenchaux** [comment]
Yes, both the documentation and the type should be changed. In my opinion, it is a use case that should be allowed by the library, so I would rethink the `once`, `consecutive` and `check` methods. What do you think?

**Comment by jsumners** [comment]
I think that is a major change and that the library probably shouldn't have been released at v1.0.0.

**Comment by ruddenchaux** [comment]
@jsumners My latest `feat: allow to pass a callback to once and consecutive` commit allows to pass a callback to `once` and `consecutive` without any breaking change. Can you review it?

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
@jsumners PTAL

**Comment by mcollina** [comment]
(wrong button, sorry)

**Review by jsumners — APPROVED** [review]

**Pull request merged**
